version: "3"

services:
  postgres:
    image: postgres:15.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
#  prometheus:
#    image: prom/prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - 9090:9090

  user:
    build: .
    volumes:
      - ./internal:/internal
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - GRPC_PORT=5001
    working_dir: /internal/user
    env_file:
      - .env
    depends_on:
      - postgres
  gateway:
    build: .
    volumes:
      - ./internal:/internal
    ports:
      - 8001:8001
    environment:
      - PORT=8001
    working_dir: /internal/gateway
    env_file:
      - .env
    depends_on:
      - postgres
  cart:
    build: .
    volumes:
      - ./internal:/internal
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - GRPC_PORT=5002
    working_dir: /internal/cart
    env_file:
      - .env
    depends_on:
      - postgres