// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: cart.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CartClient is the client API for Cart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartClient interface {
	AddProfile(ctx context.Context, in *AddStoreProfileRequest, opts ...grpc.CallOption) (*AddStoreProfileResponse, error)
	SynchronizeProducts(ctx context.Context, in *SynchronizeProductsRequest, opts ...grpc.CallOption) (*SynchronizeProductsResponse, error)
}

type cartClient struct {
	cc grpc.ClientConnInterface
}

func NewCartClient(cc grpc.ClientConnInterface) CartClient {
	return &cartClient{cc}
}

func (c *cartClient) AddProfile(ctx context.Context, in *AddStoreProfileRequest, opts ...grpc.CallOption) (*AddStoreProfileResponse, error) {
	out := new(AddStoreProfileResponse)
	err := c.cc.Invoke(ctx, "/genproto.Cart/AddProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) SynchronizeProducts(ctx context.Context, in *SynchronizeProductsRequest, opts ...grpc.CallOption) (*SynchronizeProductsResponse, error) {
	out := new(SynchronizeProductsResponse)
	err := c.cc.Invoke(ctx, "/genproto.Cart/SynchronizeProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServer is the server API for Cart service.
// All implementations should embed UnimplementedCartServer
// for forward compatibility
type CartServer interface {
	AddProfile(context.Context, *AddStoreProfileRequest) (*AddStoreProfileResponse, error)
	SynchronizeProducts(context.Context, *SynchronizeProductsRequest) (*SynchronizeProductsResponse, error)
}

// UnimplementedCartServer should be embedded to have forward compatible implementations.
type UnimplementedCartServer struct {
}

func (UnimplementedCartServer) AddProfile(context.Context, *AddStoreProfileRequest) (*AddStoreProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}
func (UnimplementedCartServer) SynchronizeProducts(context.Context, *SynchronizeProductsRequest) (*SynchronizeProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizeProducts not implemented")
}

// UnsafeCartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServer will
// result in compilation errors.
type UnsafeCartServer interface {
	mustEmbedUnimplementedCartServer()
}

func RegisterCartServer(s grpc.ServiceRegistrar, srv CartServer) {
	s.RegisterService(&Cart_ServiceDesc, srv)
}

func _Cart_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStoreProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.Cart/AddProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).AddProfile(ctx, req.(*AddStoreProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_SynchronizeProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).SynchronizeProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.Cart/SynchronizeProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).SynchronizeProducts(ctx, req.(*SynchronizeProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cart_ServiceDesc is the grpc.ServiceDesc for Cart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.Cart",
	HandlerType: (*CartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProfile",
			Handler:    _Cart_AddProfile_Handler,
		},
		{
			MethodName: "SynchronizeProducts",
			Handler:    _Cart_SynchronizeProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
